### ISSUE TITLE
Circular geometries turning square

### ISSUE THREAD

**Issue by emaartensson** [fusion-energy/cad_to_dagmc#25]
Hello, 

I am running neutronics simulations on a tokamak center column shield with some arbitrary, circular, cooling pipes in them using cad_to_dagmc to convert my step-file. The CAD looks like below: 
![image](https://user-images.githubusercontent.com/119273105/227076075-0c674d8b-1407-4319-8270-00dcfdfc225c.png)

When I plot the geometry using openmc, however, the cooling pipes are suddenly very square. Is this simply a plotting issue or do you think the geometry as a whole is wrong for the actual neutronics simulations as well? 
![image](https://user-images.githubusercontent.com/119273105/227076015-2505ba81-580e-47a8-bc0d-ce4ab52eb414.png)

**Comment by shimwell** [comment]
Great image, love the I instantly thought 🍉

thanks for trying this package and the feedback 

Just wondering if it is worth reducing the mesh sizes

max_mesh_size and min_mesh_size get passed to gmsh and might help make the mesh follow the geometry closer
```
my_model.export_dagmc_h5m_file(
    filename="dagmc.h5m", max_mesh_size=0.2, min_mesh_size=0.1
)
```

**Comment by emaartensson** [comment]
Yep that did the trick, thank you! I probably should have figured that out myself. 

(sorry for changing colours!) 
![image](https://user-images.githubusercontent.com/119273105/227390304-73341067-cefd-4ed0-b825-ef499f624d51.png)

**Comment by shimwell** [comment]
Excellent, perhaps I should change the default settings.

Here is a link to a package you might be interested in for plotting geometry in specific colors
https://github.com/fusion-energy/openmc_geometry_plot/blob/2196db150aa19b7a612baaaa88a2dbfdea404584/examples/dagmc_tokamak/plot.py#L29-L49
