### ISSUE TITLE
AttributeError when using export_dagmc_h5m_file

### ISSUE THREAD

**Issue by rlbarker** [fusion-energy/cad_to_dagmc#73]
I am converting cadquery geometry to a dagmc h5m file, and I keep getting the following error:

```
AttributeError: 'OCP.TopoDS.TopoDS_Compound' object has no attribute '_address'
```

The error comes from the following lines of code in cad_to_dagmc:
```python
gmsh, volumes = _mesh_brep(
            brep_object=imprinted_assembly.wrapped._address(),  # in memory address
            min_mesh_size=min_mesh_size,
            max_mesh_size=max_mesh_size,
            mesh_algorithm=mesh_algorithm,
        )
```
Has anyone seen this problem before?

I believe it must be to do with my environment - I am using github codespaces to run this.  This is because when I run the exact same code on my local computer in an environment that I made following the same install order as the codespace it runs fine.  My Dockerfile in the codespace installs the relevant packages like this:

```bash
RUN apt-get --yes install libeigen3-dev \
                        #   sudo  \
                          # sudo is needed during the NJOY install
                          git \
                          wget \
                          gfortran \
                          g++ \
                          mpich \
                          libmpich-dev \
                          libhdf5-serial-dev \
                          libhdf5-mpich-dev \
                          hdf5-tools \
                          imagemagick \
                          cmake \
                          # libnetcdf-dev is needed to allow NETCDF on MOAB which helps with tet meshes in OpenMC
                          libnetcdf-dev \
                          # libtbb-dev required for DAGMC
                          libtbb-dev \
                          # libglfw3-dev required for DAGMC
                          libglfw3-dev \
                          # needed for CadQuery functionality
                          libgl1-mesa-glx \
                          # needed for CadQuery functionality
                          libgl1-mesa-dev \
                          # needed for CadQuery functionality
                          libglu1-mesa-dev \
                          # needed for CadQuery functionality
                          freeglut3-dev \
                          # needed for CadQuery functionality
                          libosmesa6 \
                          # needed for CadQuery functionality
                          libosmesa6-dev \
                          # needed for CadQuery functionality
                          libgles2-mesa-dev \
                          # needed for Gmsh functionality
                          libxft2

# installing cadquery and jupyter 
RUN conda install -c conda-forge -c python python=3.10

RUN conda install mamba

RUN mamba install -y -c conda-forge "moab>=5.3.0" gmsh python-gmsh
RUN pip install cad_to_dagmc==0.6.2

RUN mamba install -c conda-forge -y "openmc=0.14.0=dagmc*nompi*"
RUN pip install openmc_data_downloader

RUN pip install cadquery
```

Many thanks

**Comment by shimwell** [comment]
Thanks for reporting. I've senn this error when older versions of ocp have been used. I thought this package brought in ocp 7.7.2 or newer but I should do some digging to be sure.

**Comment by rlbarker** [comment]
Interesting, thanks - I will try to work out which version I have in my environment.

**Comment by rlbarker** [comment]
I did conda list, and it showed:
```
ocp                       7.7.2.0         py310hc0337cc_2    conda-forge
```
when I import ocp and print the version I get no module named ocp, Module not found error.  Weird, as I've selected the same environment for my jupyter notebook.  I will investigate more

**Comment by rlbarker** [comment]
ah ok, didn't realise OCP had to be in capitals, it would appear my jupyter notebook is using OCP version 7.7.0.0.  So I need to update that!

**Comment by shimwell** [comment]
Interesting stuff, is this all with python 3.10 or newer and Ubuntu 22.04 or newer. I think cadquery-ocp 7.7.2 needs a new ish setup. The ocp github is also split into two repos. But I posted this issue which might be related https://github.com/CadQuery/ocp-build-system/issues/24

**Comment by rlbarker** [comment]
All python 3.10.  So far I've worked out that the pip install gives me 7.7.0 and the conda install gives me 7.7.2 I think, need to test a little more to confirm.

**Comment by rlbarker** [comment]
It does look very similar to that issue yes - must be something in my codespace environment/setup.
