### ISSUE TITLE
Include multi-thread meshing for gmsh to accelerate process

### ISSUE THREAD

**Issue by rherrero-pf** [fusion-energy/cad_to_dagmc#81]
gmsh allows for certain algorithms to parallelize the meshing operation, e.g. of possible implementation
  
```
gmsh.option.setNumber("Mesh.MaxNumThreads1D", number_of_threads)
gmsh.option.setNumber("Mesh.MaxNumThreads2D", number_of_threads)
gmsh.option.setNumber("Mesh.MaxNumThreads3D", number_of_threads)
```

**Comment by shimwell** [comment]
Thanks for raising an issue. I agree it would be great to speed up the meshing in this way. Are you keen to make a PR for this issue
